#!/usr/bin/python3
import sys
import psycopg2

db = 'uni'
conn = None

if len(sys.argv) != 2:
    print('usage: ./nsubjects pattern')
    sys.exit(1)

pattern = sys.argv[1]

mataching_school_query = 'select longname from orgunits where longname ilike %s'
num_subjects_query = '''
    select count(*)
    from subjects as s
    join orgunits as o on s.offeredby = o.id
    where o.longname = %s
'''

try:
    conn = psycopg2.connect(f"dbname={db}")
    cur = conn.cursor()
    
    # find what schools match
    cur.execute(mataching_school_query, ('%' + pattern + '%',))
    matches = cur.fetchall()

    if len(matches) == 0:
        print('no matches')
    elif len(matches) > 1:
        print('Multiple schools match:')
        for match in matches:
            print(match[0])
    else:
        school = matches[0][0]
        cur.execute(num_subjects_query, (school,))
        num_subjects = cur.fetchone()
        print(f'{school} teaches {num_subjects} subjects')

    cur.close()
except psycopg2.Error as err:
    print("database error: ", err)
finally:
    if conn is not None:
        conn.close()